openapi: 3.0.0

info:
  title: Egenmeldt sykmelding API
  description: API for egenmeldt sykmeldinger.
  version: 1.0.0
servers:
  - url: 'https://egenmeldt-sykmelding-backend.nais.preprod.local'

paths:
  /api/v1/sykmelding/egenmeldt:
    post:
      operationId: createEgenmeldtSykmelding
      description: Opprett ny egenmeldt sykmelding
      security:
        - bearerAuth: []
      requestBody:
        $ref: '#/components/requestBodies/CreateEgenmeldtSykmelding'
      responses:
        '201':
          description: Created
        '400':
          $ref: '#/components/responses/CreateEgenmeldtSykmeldingBadRequest'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /api/v1/arbeidsforhold:
    get:
      operationId: getArbeidsforhold
      description: henter arbeidsforhold for innlogget bruker
      security:
        - bearerAuth: []
      responses:
        '200':
          $ref: '#/components/responses/ArbeidsforholdResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden

components:
  requestBodies:
    CreateEgenmeldtSykmelding:
      description: Egenmeldt Sykmelding data object
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/EgenmeldtSykmelding'

  responses:
    ArbeidsforholdResponse:
      description: liste med arbeidsforhold for innlogget bruker
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Arbeidsforhold'
    CreateEgenmeldtSykmeldingBadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            type: object
            properties:
              errors:
                type: array
                items:
                  type: object
                  properties:
                    message:
                      type: string
  schemas:
    Arbeidsforhold:
      type: object
      required:
        - navn
        - orgNummer
        - juridiskOrgNummer
        - stillingsprosent
      properties:
        navn:
          type: string
        orgNummer:
          type: string
        juridiskOrgNummer:
          type: string
        stillingsprosent:
          type: number
          example:
            80.5
    EgenmeldtSykmelding:
      type: object
      properties:
        periode:
          $ref: '#/components/schemas/EgenmeldtPeriode'
        arbeidsforhold:
          type: array
          items:
            $ref: '#/components/schemas/Arbeidsforhold'
    EgenmeldtPeriode:
      type: object
      description: Perioden for egenmeldt sykmelding. Fom = fra og med, tom = til og med
      properties:
        fom:
          $ref: '#/components/schemas/Date'
        tom:
          $ref: '#/components/schemas/Date'
    Date:
      type: string
      format: date
security:
  - bearerAuth: []
