apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: egenmeldt-sykmelding-backend
  namespace: default
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 400m
      memory: 768Mi
  vault:
    enabled: true
    paths:
      - kvPath: /azuread/data/dev/creds/egenmeldt-sykmelding-backend
        mountPath: /secrets/azuread/egenmeldt-sykmelding-backend
      - kvPath: serviceuser/data/dev/srvegenmeldt
        mountPath: /secrets/serviceuser
      - kvPath: /kv/preprod/fss/egenmeldt-sykmelding-backend/default
        mountPath: /var/run/secrets/nais.io/vault
  ingresses:
    - "https://egenmeldt-sykmelding-backend.nais.preprod.local"
  webproxy: true
  env:
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443
    - name: MQ_HOST_NAME
      value: b27apvl173.preprod.local
    - name: MQ_PORT
      value: '1413'
    - name: MQ_GATEWAY_NAME
      value: MQ1LSC03
    - name: MQ_CHANNEL_NAME
      value: Q1_EGENMELDT
    - name: MQ_SYFOSERVICE_QUEUE_NAME
      value: QA.Q1_EIA_SYFO_OUTBOUND
    - name: EGENMELDT_SYKMELDING_BACKEND_DB_URL
      value: jdbc:postgresql://b27dbvl013.preprod.local:5432/egenmeldt-sykmelding-backend
    - name: MOUNT_PATH_VAULT
      value: /postgresql/preprod-fss

